# 测试环境配置文件

server:
  addr: ":8080"
  mode: "debug"
  read_timeout: "10s"
  write_timeout: "10s"

database:
  driver: "postgres"
  
  postgres:
    host: "1.95.88.239"
    port: 5432
    user: "uac"
    password: "j4x3mdzttNnanCsB"
    dbname: "uac"
    sslmode: "disable"

redis:
  addr: "1.95.88.239:6379"
  password: "123456"
  db: 0

jwt:
  private_key_path: "./configs/keys/private.pem"
  public_key_path: "./configs/keys/public.pem"
  issuer: "unified-auth-center"
  access_expiry: "2h"
  refresh_expiry: "168h"
